# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maxim/projects/psystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maxim/projects/psystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxim/projects/psystem/CMakeFiles /home/maxim/projects/psystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxim/projects/psystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psdistance

# Build rule for target.
psdistance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psdistance
.PHONY : psdistance

# fast build rule for target.
psdistance/fast:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/build
.PHONY : psdistance/fast

#=============================================================================
# Target rules for targets named psystem

# Build rule for target.
psystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psystem
.PHONY : psystem

# fast build rule for target.
psystem/fast:
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/build
.PHONY : psystem/fast

intersections/intersections.o: intersections/intersections.cpp.o

.PHONY : intersections/intersections.o

# target to build an object file
intersections/intersections.cpp.o:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/intersections/intersections.cpp.o
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/intersections/intersections.cpp.o
.PHONY : intersections/intersections.cpp.o

intersections/intersections.i: intersections/intersections.cpp.i

.PHONY : intersections/intersections.i

# target to preprocess a source file
intersections/intersections.cpp.i:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/intersections/intersections.cpp.i
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/intersections/intersections.cpp.i
.PHONY : intersections/intersections.cpp.i

intersections/intersections.s: intersections/intersections.cpp.s

.PHONY : intersections/intersections.s

# target to generate assembly for a file
intersections/intersections.cpp.s:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/intersections/intersections.cpp.s
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/intersections/intersections.cpp.s
.PHONY : intersections/intersections.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/main.cpp.s
.PHONY : main.cpp.s

psdistance.o: psdistance.cpp.o

.PHONY : psdistance.o

# target to build an object file
psdistance.cpp.o:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psdistance.cpp.o
.PHONY : psdistance.cpp.o

psdistance.i: psdistance.cpp.i

.PHONY : psdistance.i

# target to preprocess a source file
psdistance.cpp.i:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psdistance.cpp.i
.PHONY : psdistance.cpp.i

psdistance.s: psdistance.cpp.s

.PHONY : psdistance.s

# target to generate assembly for a file
psdistance.cpp.s:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psdistance.cpp.s
.PHONY : psdistance.cpp.s

psystem.o: psystem.cpp.o

.PHONY : psystem.o

# target to build an object file
psystem.cpp.o:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psystem.cpp.o
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/psystem.cpp.o
.PHONY : psystem.cpp.o

psystem.i: psystem.cpp.i

.PHONY : psystem.i

# target to preprocess a source file
psystem.cpp.i:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psystem.cpp.i
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/psystem.cpp.i
.PHONY : psystem.cpp.i

psystem.s: psystem.cpp.s

.PHONY : psystem.s

# target to generate assembly for a file
psystem.cpp.s:
	$(MAKE) -f CMakeFiles/psdistance.dir/build.make CMakeFiles/psdistance.dir/psystem.cpp.s
	$(MAKE) -f CMakeFiles/psystem.dir/build.make CMakeFiles/psystem.dir/psystem.cpp.s
.PHONY : psystem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... psdistance"
	@echo "... rebuild_cache"
	@echo "... psystem"
	@echo "... intersections/intersections.o"
	@echo "... intersections/intersections.i"
	@echo "... intersections/intersections.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... psdistance.o"
	@echo "... psdistance.i"
	@echo "... psdistance.s"
	@echo "... psystem.o"
	@echo "... psystem.i"
	@echo "... psystem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

